name: dialyzer

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      repository:
        description: "elixir source repo to check out"
        required: false
        default: "michallepicki/elixir"
      ref:
        description: "elixir source ref to check out"
        required: false
        default: "patch-1"

jobs:
  dialyzer:
    strategy:
      matrix:
          otp_release: ['24.3.4.6', '25.1.1']
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install erlang
        run: |
          echo "`pwd`/erlang/bin" >> $GITHUB_PATH
          curl -Lo erlang.tar.gz https://repo.hex.pm/builds/otp/ubuntu-20.04/OTP-${{ matrix.otp_release }}.tar.gz
          mkdir erlang
          tar zxf erlang.tar.gz -C erlang --strip-components=1
          erlang/Install -minimal  `pwd`/erlang
          rm erlang.tar.gz

      - name: Get elixir source code
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository || 'elixir-lang/elixir' }}
          ref: ${{ github.event.inputs.ref || 'main' }}
          path: elixir

      - name: Compile elixir
        run: |
          cd elixir
          make compile
          cd ../

      - name: Handle otp PLT file caching
        uses: actions/cache@v2
        with:
          path: plt-dir/${{ matrix.otp_release }}.plt
          key: v2-OTP-${{ matrix.otp_release }}

      - name: Check Elixir
        run: elixir/bin/elixir dialyzer.exs

      - name: Save the report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.otp_release }}-report
          path: report
