name: dialyzer

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      repository:
        description: "elixir source repo to check out"
        required: false
        default: "michallepicki/elixir"
      ref:
        description: "elixir source ref to check out"
        required: false
        default: "patch-1"

jobs:
  dialyzer:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install erlang
        run: |
          echo "`pwd`/erlang/bin" >> $GITHUB_PATH
          curl -Lo erlang.tar.gz https://repo.hex.pm/builds/otp/ubuntu-20.04/OTP-24.1.3.tar.gz
          mkdir erlang
          tar zxf erlang.tar.gz -C erlang --strip-components=1
          erlang/Install -minimal  `pwd`/erlang
          rm erlang.tar.gz

      - name: Get elixir source code
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository || 'elixir-lang/elixir' }}
          ref: ${{ github.event.inputs.ref || 'master' }}
          path: elixir

      - name: Compile elixir
        run: |
          cd elixir
          make compile
          cd ../

      - name: Handle otp PLT file caching
        id: cache-plt
        uses: actions/cache@v2
        with:
          path: plt-dir/otp.plt
          key: v1-OTP-24.1.3

      - name: Create the dialyzer PLT file
        if: steps.cache-plt.outputs.cache-hit != 'true'
        run: dialyzer --output_plt plt-dir/otp.plt --build_plt --apps erts kernel stdlib compiler syntax_tools parsetools tools ssl inets crypto runtime_tools ftp tftp mnesia public_key asn1 sasl

      - name: Check Elixir
        run: elixir/bin/elixir dialyzer.exs

      - name: Save the report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report
